kufu/hello-world

- src/components/commandPalette/CommandPaletteUI.tsx
- コマンドパレットをタイトルより前面に表示
- Before
- <img width="1120" alt="Screen Shot 2020-02-09 at 13 41 29" src="https://user-images.githubusercontent.com/38120991/74096573-0d3a3800-4b44-11ea-8dd5-34a6a8235375.png">
- After
- <img width="1118" alt="Screen Shot 2020-02-09 at 13 48 44" src="https://user-images.githubusercontent.com/38120991/74096581-19be9080-4b44-11ea-9b90-0b728a96fee4.png">
- `z-index` で調整するのがいいのかちょっとわからないです 🤔
> コマンドパレットをタイトルより前面に表示

- src/components/parts/SectionTitle.tsx
- src/themes/index.ts
- src/themes/size.ts
タブレット・スマホへのレスポンシブ対応のための styled-components の styled 内で使える関数を用意しました。
こんな感じで使います。
```
${mediaQuery.mediumStyle(css`
font-size: 36px;
`)}
```
mediumStyle, smallStyle 内に styled-components の css 関数を隠蔽しても良かったのですが styled-components の syntax highlight がそのまま使えた方が良いかなとという考えの元、 css 関数は mediumStyle, smallStyle を使う側で引数に入れてもらうようにしました。
最初に PC のコーディングをしているので、 PC ファーストで特定のサイズ以下になったらスタイルを追加で付与する、という形にしていく想定です。なので、現状は PC サイズのみ指定するスタイル、のようなことはできません。進めていく中でそれが必要になりそうなシーンがあれば追加するという形で考えています。
- 全サイズ適用のスタイル
- innerWidth が1199px以下のスタイル
- innerWidth が 739px以下でのスタイル
という感じになっています。
2つの数字に関しては、 inVision を見ながら横幅を狭めていって破綻しそうなところで切り替わるように、というところで選びました。
試しに SectionTitle の font-size をタブレットサイズ用に切り替えるスタイルを入れています。
> タブレット・スマホ対応のための便利関数を作成

- src/components/App.tsx
- src/components/parts/EntrySection.tsx
- src/components/parts/MembersVoiceSection.tsx
- src/components/parts/MessageSection.tsx
- src/components/parts/TechnologyStackSection.tsx
- src/components/parts/WelfareSection.tsx
- messageセクションのモバイル調整
- mobile調整しやすいように画像や幅に`width: 100%`を指定（mobile調整後削除します。）
[Tablet design](https://smarthr.invisionapp.com/d/main#/console/18984751/397682813/preview)
[SP design](https://smarthr.invisionapp.com/d/main#/console/18984751/397682812/preview)
<details>
<summary>Tablet</summary>
</details>
<details>
<summary>SP</summary>
</details>
> messageセクションのモバイル調整

- src/components/hooks/useEventListener.ts
- src/components/hooks/useStoredScroll.ts
- src/components/pages/index.tsx
- src/components/parts/EyeCatchEffects.tsx
- src/themes/index.ts
- src/themes/size.ts
- Underlay として置いているバックグラウンドイメージのフェードアウトをスクロールに合わせることでもっと気持ち良くしたい
- スクロールのアイコンのアニメーションをヌルッとさせたい
- バックグラウンドイメージにスクロールの量に合わせて計算した opacity を当てた
- スクロールアイコンのアニメーションを keyframes を調整した
- スクロールアイコンを特定の位置までスクロールしたらフェードアウトさせるようにした
ヌルッと感が伝わる gif にしようとするとファイルサイズがどうあってもデカすぎて貼れなかったのでローカルで動かして動作確認してください 🙏
> バックグラウンドイメージとスクロールアニメーションアイコンの調整

- src/components/parts/Accordion.tsx
現状だとアコーディオンの全てがクリックのトリガーとなっており、アコーディオンの中身をクリックした時も発動してアコーディオンが閉じてしまうのでちょっと不便。
テキスト選択したりとか不意にクリックしてしまった時に閉じちゃうとハッてなっちゃいそう…！
なのでタイトル部分のみをクリック領域にしたい。
- クリックの領域をタイトル部分に絞った
- タイトル部分を role="button" にした
本当は onClick の部分は button に変えるのが最善な気がするけど対応がちょっと大変そうだったので今回はそのままにして role だけの対応としました。
> アコーディオンのトリガーをタイトル部分だけに絞る

- src/components/parts/WelfareSection.tsx
- static/images/welfare/window_icon.svg
welfareセクションのiconを差し替えました。
<details>
<summary>PC</summary>
</details>
<details>
<summary>Tablet</summary>
</details>
<details>
<summary>SP</summary>
</details>
> feat(welfare): welfareセクションのicon差し替え

- src/components/hooks/useEventListener.ts
- src/components/hooks/useStoredScroll.ts
- src/components/parts/EyeCatchEffects.tsx
- src/themes/size.ts
静的ビルド時は window オブジェクトが存在しないので、 window オブジェクトにぶら下がっているメソッドや値を呼ぶ際に window オブジェクトの存在確認をする。
参考: https://www.gatsbyjs.org/docs/debugging-html-builds/
> Gatsby の静的ビルドで動かないコードの修正

- src/components/parts/AboutSection.tsx
- src/components/parts/TechnologyStackSection.tsx
pc
tablet
mobile
pc
tablet
mobile
> Technology Stack の margin-top を調整

- src/components/parts/MembersVoiceSection.tsx
Members Voiceのエンジニアリンク、hover時にunderlineが消えるように修正しました。
<details>
<summary>BEFORE</summary>
</details>
<details>
<summary>AFTER</summary>
</details>
> refactor: hover時にunderlineが消えるように修正

- .env.development
- gatsby-browser.js
- gatsby-ssr.js
初期起動時に development 環境の場合、 GatsbyWrapper の中身の存在を保証できないため、ローディング処理はプロダクションビルドの時のみに限定する。
> :bug: dev と prd で起動時のローディングを出し分ける

- src/components/parts/WelfareSection.tsx
福利厚生のリモートワークに関する説明が「before コロナ」なものだったので、「with コロナ」なものにアップデートしたい
こんな感じで文言とリンクを差し替えました。
**before**
**after**
> リモートワークに関する説明をアップデートしました

- src/components/parts/TechnologyStackSection.tsx
- Technology Stack 部分のテキストの「元」を「もと」に変更
- 恐らく漢字的には「下」が正しいと思うんですが、「以下の技術スタックの下に」だと「下」が連続で出現してやや読みづらい気がしたので平仮名にしました。
> Technology Stack 部分のテキストを修正

- src/components/parts/TechnologyStackSection.tsx
```
開発に必要な技術は、現場の担当エンジニアがユーザとシステムにとって最適な技術を選定しています。
```
↓
```
開発に必要な技術は、現場の担当エンジニアがユーザとシステムにとって最適なものを選定しています。
```
`開発に必要な技術` のあとに `最適な技術` と続いていて、技術が二度登場していて違和感があったので後者を `もの` としました。
> Technology Stack Section のテキストを修正

- src/pages/index.tsx
title が `Engineer Recruiting | SmartHR` となっていたので、og:title に合わせて  `SmartHR エンジニア採用` とした
> title の文字列を og:title と合わせる

- src/components/pages/ie.tsx
style 属性でスタイルを当てるようにしたが、 Gatsby の仕様なのかルートにあたるコンポーネントが上書きされてしまいスタイルが当たらなかったので、根本対応ではないが一旦の策として空の div でネストさせてみる
> やっぱりまだ IE でスタイルが崩れていたのを修正

- src/components/parts/MembersVoiceSection.tsx
kinoppyd さんのアカウント名の前に `@` が抜けていたので追加しました
before
after
> Members Voice のアカウント名の修正

- src/components/commandPalette/commands/ImageEffect.tsx
Chrome で DevTool を開いていないときだけ `window.addEventListener('resize', drawImageOnCanvas)` のコールバックが呼ばれないという謎の現象が発生していたので動くように修正しました。
未だに原因は不明ですが、動くように書き直した結果コードはきれいになりました。
> :bug: Chrome でなぜか resize イベントのコールバックが動かなかったので修正

- src/components/parts/BenefitsSection.tsx
「感染症対策、リモートワークについて」の記事は古くなっているので削除しました。
| before | after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/7158259/99632902-6050fc00-2a81-11eb-9475-94ab52bd59b9.png) | ![image](https://user-images.githubusercontent.com/7158259/99632876-4f07ef80-2a81-11eb-9729-cdc87cb26220.png) |
> Remove 「感染症対策、リモートワークについて」 link

- src/components/parts/BenefitsSection.tsx
組織外から失礼します。
「SmartHR会社紹介資料」にスライドが追加された影響で、「その他の福利厚生」リンクの遷移先が「参考: プラットフォーム化構想」になっていたため修正いたしました。
> fix: 「その他の福利厚生」のリンク先を修正

- src/components/parts/BenefitsSection.tsx
資料が修正された影響で「その他の福利厚生」のリンク先が「福利厚生の考え方」のスライドになっていたようなので修正しました！
> その他の福利厚生のリンク先を修正

- src/components/parts/EyeCatch.tsx
このページから GitHub に飛べた方が面白そうなので追加しました。
PC 表示の時だけ表示されます。
配置としては見つけて欲しいので ENTRY ボタンの隣に置いていますが、 ENTRY ボタンよりは重要度が低いので見た目はただのテキストリンクにしています。
スマホ表示の時のリンクの置き場所に困ったという問題がまずあり、そしてスマホで見た時に GitHub 飛べてもあんまり嬉しくなさそうとかそもそも採用サイト見るエンジニアは PC で見そうだしいっか、と思いスマホでは表示されません。
割と雰囲気でやったのでだめそうなら reject してください 🙏
> GitHub へのリンクを追加

- src/components/parts/Accordion.tsx
- src/components/parts/EyeCatchEffects.tsx
本サイトは、見たところほぼすべてのインタラクションに transition が設定されていますが、 Members Voice セクションのアコーディオンの開閉時において、矢印のアニメーションの transition が設定されておらずパッと切り替わることに違和感を覚えましたので、 transition を設定してみました。
上記の対応を取ることで、アコーディオン開閉自体の動きと同調し、自然な動きになるかなと思います。
有益なコードの公開、ありがとうございます！
サイトを拝見していて少し気になったので、改善案をプルリクさせていただきました。
ご一考いただけますと幸いです。
> アコーディオン開閉時の矢印のアニメーションを微調整

- src/components/parts/EyeCatchEffects.tsx
ファーストビューで見えている SCROLL アイコンが、メッセージテキストの冒頭に被って見える場合があったため、 SCROLL アイコンを非表示にするスクロール位置を調整してみました。
なお、オーバーレイが表示されるタイミングはそのままとしています。
有益なコードの公開、ありがとうございます！
サイトを拝見していて少し気になったので、改善案をプルリクさせていただきました。
ご一考いただけますと幸いです。
> KV の SCROLL アイコンがメッセージの冒頭に干渉しないよう、非表示の位置を調整

- src/components/parts/BenefitsSection.tsx
採用資料がアップデートされていて、福利厚生ページのURLが変わっていたため修正しました！
この仕様は脆いなー…
> fix: URL to the benefits page

- src/components/parts/EntrySection.tsx
マージンを足させていただきました
spanに余白がないので文字がかぶって見えていました
余白を設け、かぶって見えない程度に調整しました
> feat: add margin to EntrySection item

- src/components/parts/EntrySection.tsx
QA及びテストエンジニアの募集職種名称が以下のように変更になりました。
エンジニア採用サイトでも同じ名称にしたいので変更します。
**変更内容**
QA(品質保証) → QAエンジニア
テストエンジニア(Software Engineer in Test) → SET(Software Engineer in Test)
> 募集職種名が変更になったので合わせる

- src/components/commandPalette/commands/ImageEffect.tsx
- src/components/hooks/useWebp.ts
- src/components/parts/EyeCatchEffects.tsx
WebP の判定が非同期で呼ばれる関係で、PNGとWebPの両方がダウンロードされています。
フロー
1. useWebp を呼ぶ
2. onload が動作する前に false を返す
3. png 画像のダウンロードを始める
4. onload が動作し、useWebp が true になる
5. webp 画像のダウンロードを始める
mv.png はサイズが大きいのでできればダウンロードをしたくありません。useWebp の判定が行われるまでは画像に空文字列を指定しておき、ダウンロードが走らないようにしました。
> PNG, WebP の画像を両方取得している問題を修正

- netlify.toml
Netlify はレスポンスヘッダーに `cache-control: public, max-age=0, must-revalidate` をつけるので、結果として Cloudflare のキャッシュが有効に動作せず、直接 netlify にアクセスするよりも遅い状態になっています。
hello-world.smarthr.co.jp
netlify直接アクセス
経路・ブラウザでのキャッシュを有効化するために、netlify のレスポンスヘッダー設定を変更しました。
以下のルールにしていますが、キャッシュ期間についてはコメントがあればいただきたいです:
- デフォルトで1時間キャッシュ
- ファイル名にダイジェストを含むファイルは内容が変わったときにパスが変わるので、長期間（1年間）キャッシュ
> ブラウザ・CDNでコンテンツをキャッシュさせるヘッダーを設定

- src/components/commandPalette/commands/ImageEffect.tsx
隠しコマンドで glitch と starry night を選択したときにエフェクトが表示されないバグを直したい
webp が使えるかどうかのフラグが画像の読み込み部分とうまいこと噛み合っていなかったので条件分岐を変えた。
いつからここが動かなくなっていたのかはわからない…
Cmd + Shift + P でコマンドパレットが出るので、その後「glitch」と「starry night」を選択してエフェクトが発生するかを確認する
> 隠しコマンドのエフェクトが表示されないバグを修正

- src/components/commandPalette/CommandPaletteUI.tsx
Use `KeyboardEvent.key` instead of `KeyboardEvent.keyCode`.
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
See also:
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent#obsolete_properties
> Warning: This attribute is deprecated; you should use KeyboardEvent.key instead, if available.
There is a similar property `KeyboardEvent.code`.
It represents a physical key on the keyboard and is not used here.
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
> The KeyboardEvent.code property represents a physical key on the keyboard (as opposed to the character generated by pressing the key). In other words, this property returns a value that isn't altered by keyboard …
> Avoid obsolete property on `KeyboardEvent`

- src/components/parts/EntrySection.tsx
広報物の表記統一のため「ウェブアプリケーションエンジニア」に統一したいです！
> 「Webアプリケーションエンジニア」→「ウェブアプリケーションエンジニア」に変更したい

- src/components/parts/EntrySection.tsx
コーポレートエンジニアは現在募集を停止しており、エントリーページが閲覧できない状態です。
そのため、採用サイトからも動線を消してしまいます。
> コーポレートエンジニアは募集停止中なのでリンクを隠す

- src/components/parts/BenefitsSection.tsx
40だとここ
https://speakerdeck.com/miyasho88/we-are-hiring?slide=40
今は38が多分正しいはず！
https://speakerdeck.com/miyasho88/we-are-hiring?slide=38
> 福利厚生のページが40から38に変わってるので追従

- src/components/commandPalette/CommandPalette.tsx
サイトとソースコードを閲覧していたところコマンドパレットの機能があるのを見つけて使おうとしましたが  
Win端末ではcommandキーが存在せず、コマンドパレットが開けなかったため修正してみました。
端末を判定して呼び出すキーを変更する処理にしようとも思いましたが[`Navigator.platform`](https://developer.mozilla.org/ja/docs/Web/API/Navigator/platform)が既に非推奨になっていることとUA判定自体が推奨されない操作なので`Ctrl+Shift+P`でも呼び出せるように変更してみました。
もしよろしければご確認お願いします🙇
| OS | Browser |
|---|---|
| Windows 10 Version 21H2 (Build 19044.1826) |  Google Chrome 103.0.5060.114 |
> Win環境ではコマンドパレットが開けないようなので修正

- src/components/parts/BenefitsSection.tsx
https://speakerdeck.com/miyasho88/we-are-hiring?slide=38
から
https://speakerdeck.com/miyasho88/we-are-hiring?slide=35
に変わっていました。
> 福利厚生のページが変わっていたので追従

- src/components/parts/EntrySection.tsx
* プラットフォーム開発エンジニアの求人リンクを追加したい
* Talentioで発行されるリンクが変わってたので直したい
* リダイレクトは効いてるっぽかったのですが、いちおう…
* 求人票のタイトルとリンクテキストが違うところをなんとかしたい
* 求人票側の変更を反映できてませんでした
↑ の対応です、よろしくおねがいします
| Before | After |
| --- | --- |
| <img width="1808" alt="image" src="https://user-images.githubusercontent.com/24504765/225210236-3820d216-e520-408c-ae2e-6bf842d4601a.png"> | <img width="1808" alt="image" src="https://user-images.githubusercontent.com/24504765/225210215-3af49e20-4926-4c69-80f7-13d4bba5f604.png">|
> 求人内容を調整・追加したい

- src/components/parts/EntrySection.tsx
ウェブアプリケーションエンジニア（バックエンド）とプラットフォーム開発エンジニア（フロントエンド）のリンクを開くと、「入力されたURLページが存在しません。」と表示されるので、正しい情報に修正したい。
- ウェブアプリケーションエンジニア（バックエンド）のURLを[ウェブアプリケーションエンジニア（オープンポジション バックエンド）](https://open.talentio.com/r/1/c/smarthr/pages/82214)に変更
- プラットフォーム開発エンジニア（フロントエンド）を非表示にする
- CLOSEされたので
| Before | After |
| --- | --- |
| ![image](https://github.com/kufu/hello-world/assets/45530245/7a656859-fd07-4872-b645-44b95b9a4554) | ![image](https://github.com/kufu/hello-world/assets/45530245/39b7b95c-2aa9-4b8e-971a-9921336cafda) |
- ウェブアプリケーションエンジニア（バックエンド）をウェブアプリケーションエンジニア（オープンポジション バックエンド）という名称に変更すること
- 改行しないと表示できなさそうだったので、とりあえずリンクを復活させることを最優先として対応しませんでした
- その他の追加された求人を追加すること
> 求人情報をアップデート

- src/components/parts/EntrySection.tsx
#137 でバックエンドの求人のURLを変更したが、フロントエンドは対応していなかったので対応したい。
- ウェブアプリケーションエンジニア（フロントエンド）のURLを[ウェブアプリケーションエンジニア（オープンポジション フロントエンド）](https://open.talentio.com/r/1/c/smarthr/pages/82223)に変更
- ウェブアプリケーションエンジニア（フロントエンド）をウェブアプリケーションエンジニア（オープンポジション フロントエンド）という名称に変更すること
> ウェブアプリケーションエンジニア（フロントエンド）のリンク先を変更

- src/components/parts/EntrySection.tsx
求人情報を追加したい
以下の情報を追加。
- [ウェブアプリケーションエンジニア（労務領域 バックエンド）](https://open.talentio.com/r/1/c/smarthr/pages/82193)
- [ウェブアプリケーションエンジニア（労務領域 フロントエンド）](https://open.talentio.com/r/1/c/smarthr/pages/82217)
- [ウェブアプリケーションエンジニア（タレントマネジメント領域 バックエンド）](https://open.talentio.com/r/1/c/smarthr/pages/82188)
- [ウェブアプリケーションエンジニア（タレントマネジメント領域 フロントエンド）](https://open.talentio.com/r/1/c/smarthr/pages/82220)
また、既存のウェブアプリケーションエンジニアのバックエンドとフロントエンドの名称も変更しています。
また、名称が長くボタンのスタイルが崩れるので改行を入れるのと行間の調整をしました
| Before | After |
|:--|:--|
| <img width="622" alt="image" src="https://github.com/kufu/hello-world/assets/11153463/b17c67dd-159c-46a9-be5f-2b9d60b96fea"> | <img width="627" alt="image" src="https://github.com/kufu/hello-world/assets/11153463/910e72f0-12b0-4c5c-aa6b-30da1d4fb61f"> |
ボタンが多すぎてぱっと見わかりづらくて本当にこれで良いのか感はある…
> 求人情報の追加とスタイル調整

- src/components/sections/Document.astro
- src/components/shared/TextLink.astro
会社紹介資料のセクションを追加
- 見た目ふむふむ
- リンクをクリックして会社紹介資料の speaker deck に飛ぶこと
> 会社紹介資料セクションを追加

- src/components/sections/Header.astro
「歴史に残る模範的なソフトウェアを作ろう」のテキストとその上部の細かいテキストが、横幅を狭くしても特に違和感のない表示にしたい
- media query でフォントサイズさげたりなど
- break point はバランス見て細かい数値入れている感じです
- 特に SmartHR の一般に倣ってはいない
> header の表示がどの横幅でも崩れないようにする

- src/components/shared/MicroCMSContent.astro
外部リンクセクションの下部に人労打のバナーを配置することになったのでその対応。
`max-width: 100%;`を適用してコンテンツ幅を超過しないように制御した。
高さが大きすぎる画像に関する考慮等は特に入れていないが、現状はその手の画像を扱っていないので必要になった時にテコ入れをする。
> 外部リンクのバナー画像の対応

- src/components/parts/EntrySection.tsx
情シスセキュリティの以下の2求人が再オープンしたので、リンクを有効化したいです。
- コーポレートエンジニア
- セキュリティエンジニア
求人クローズに伴いコメントアウトしていた部分を戻しました。
「情報システムエンジニア」という名称は今回は使わないため、削除しています。
> コーポレートエンジニア & セキュリティエンジニアの求人リンクの有効化

- src/components/parts/EntrySection.tsx
求人票の名前が掲載後に変更されているので、リンク名も追従したいです！
[ウェブアプリケーションエンジニア（プラットフォーム領域 バックエンド） / 株式会社SmartHR](https://open.talentio.com/r/1/c/smarthr/pages/75921)
| 変更前 | 変更後 |
| --- | --- |
| ![image](https://github.com/kufu/hello-world/assets/24504765/8bbf564d-c58a-4afc-bac9-ba0a6c541770) | ![image](https://github.com/kufu/hello-world/assets/24504765/64daa4c0-57ea-423c-8a2d-03105827577b) |
> 求人名の変更に追従したい

- src/components/sections/Document.astro
会社紹介資料をテキストリンクから iframe 埋め込みに変更しました
ouji san には以下のスレで確認済みで、デザイン的には問題なし
https://kufuinc.slack.com/archives/C04PPFBGQHW/p1699433051770999
元の TextLink をそのまま SpeakerDeck の iframe タグに置き換えただけなのですが、それで問題ないのかわからず…
> [renewal] 会社紹介資料をテキストリンクではなく iframe 埋め込みにする

- .gitignore
- README.md
- src/services/microcms/index.ts
以下の対応を追加
- README修正
- 環境変数の設定に関しては社内向けの内容であることを明記
- API Keyを1passwordから参照してもらうよう手順を修正
- 実装の修正
- API Keyを.env.loaclになにかしら入力しないとローカル起動時に画面表示できなくなっていたので修正
- envファイルに値が入っていない（undefined）場合にエラーが置きていたのでclient生成時に環境変数が取得出来なかった場合ダミーテキストを入れるようにした
- この場合、外部リンクエリアには何のコンテンツも表示されないようになります
> 環境変数に関する修正

- package.json
- src/services/microcms/index.ts
- yarn.lock
microCMS からマークダウンを取得して HTML に変換して表示している部分がぶっ壊れているので直したい。
remark-html の更新の renovate PR に対する自分の対応が完全に間違っていました、切腹します🙏 
https://github.com/kufu/hello-world/pull/183
上記 PR が落ちていた件は、remark-html の依存にある unified と remark-parse を利用していたことが原因。
- package.json に unified と remark-parse を追加して最新にした
- https://github.com/kufu/hello-world/pull/183 で `parse` に変えたところを `process` に戻した
> markdown の parse 処理を修正

- .github/workflows/lint.yml
- package.json
- renovate.json
- yarn.lock
静的解析ツールは導入されているが、CIが導入されていなかった 😭 
これじゃあ、警告やエラーが出てても気付けないよ・・・
このPRでは、GitHub Actionsを導入してPull Requestに対して静的解析を実行するようにします。
* GitHub Actionsの導入
* 内部では `yarn lint`を実行しています
* `stylelint-config-standard`を v36.0.0 -> v34.0.0にダウングレード
* v36.0.0はstylelintのv16.1.0以上が必要
* しかし、現在stylekintはv15系を使っている
* アップデートのコストを考え、stylelint v15系が利用できるv34.0.0にダウングレードしました
* renovateでGitHub Actionsもアップデートするようにした
> Pull Requestに対してlintを実行するGitHub Actionsを導入

- src/components/sections/OrganizationalStructure.astro
「開発組織について」で埋め込まれてるmiroをfigmaに差し替えました。
差し替え先figma
https://www.figma.com/file/HFNrUtz5Bf1c52YABCxxrY/SmartHR-%E9%96%8B%E7%99%BA%E7%B5%84%E7%B9%94%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6?type=whiteboard&node-id=0%3A1&t=e01c3ZZ1qD628mY3-1
figma（figjam）の都合上、
- Readonlyで全体公開
- SmartHRアカウント持ちだけ編集可能
みたいなことができないらしく、編集権限つけるには
- 個別でつける
- 公開プロジェクト権限を付ける
のどちらかが必要になります。現時点ではどちらもやってないので、もしfigmaの内容に不備がありそうだったら修正するのでご指摘ください。
初期表示の倍率とかその辺弄る方法探してみたんですが見当たらず、とりあえずデフォルトのままになってます。
このままでもいいかな…と思ってはいますが、もし変更したほうがいいなどあれば、やり方ご存知であればぜひ…
> 埋め込みmiroをfigmaに変更

- src/layouts/Head.astro
サイトにアクセスしたときにヘッダーの「/hello-world」が表示されず、少し遅れて「/hello-world」が表示されます。ブラウザーの開発者ツールでキャッシュを切っておくと確認しやすいです。
↓
フォントの読み込みで待たされているのが原因のようです。
```
@font-face {
font-family: DINAlternateBold;
src: url('/fonts/DINAlternate-Bold.woff') format('woff');
}
```
別のフォントを代替表示することも考えたのですが試してみると違和感が大きかったので、フォントのファイル読み込みタイミングを早めることで対処しました。
ローカルで確認する場合、一度ビルドしてその内容をWebサーバーを通して参照してください。ブラウザーの開発者ツールでキャッシュを切った状態でリロードを繰り返しても文字がほとんどガタガタしないようになっているはずです。
> アクセス直後にヘッダががたつく問題を修正
