kufu/hello-world

src/components/MessageSection.tsx, src/pages/index.tsx
=> 各セクションごとにコンポーネントを用意

src/pages/index.tsx
=> スクロールアイコンのアニメーションを追加しました

src/components/App.tsx, src/components/parts/MessageSection.tsx
=> feat: Add message section

src/components/pages/index.tsx, src/components/parts/AboutSection.tsx, src/components/parts/SectionTitle.tsx, src/components/parts/TechnologyStackSection.tsx
Technology Stackコンポーネントを作成しました！
=> Add technology stack component

src/components/pages/index.tsx, src/components/parts/Accordion.tsx, src/components/parts/MembersVoiceSection.tsx
membersVoiceSectionを作成しました！
[design](https://smarthr.invisionapp.com/d/main#/console/18984751/397682814/preview)
=> feat: Add membersVoiceSection

src/components/pages/index.tsx, src/components/parts/EntrySection.tsx
=> EntrySection を実装

src/components/pages/index.tsx
=> スクロール時に背景を透過させる

src/components/parts/Footer.tsx, src/components/parts/WelfareSection.tsx
=> 福利厚生とフッターをモバイル対応

src/components/parts/TechnologyStackSection.tsx
=> TechnologyStack Section のモバイル対応

src/components/pages/index.tsx, src/components/parts/AboutSection.tsx, src/components/parts/EntrySection.tsx, src/components/parts/EyeCatch.tsx, src/components/parts/Footer.tsx, src/components/parts/MembersVoiceSection.tsx, src/components/parts/MessageSection.tsx, src/components/parts/TechnologyStackSection.tsx, src/components/parts/WelfareSection.tsx
https://github.com/kufu/hello-world/pull/28 がマージされたら取り込んで WIP 外す。 -> 済み
各セクションがユーザーのウィンドウの高さに合うことが前提のデザインだと思うので min-height を window の高さにしたい。
- 各セクションを min-height: 100vh の要素でラップした
- あといろいろとスタイル調整した
vh を使っているので多分 IE で崩壊すると思うのでここら辺を後々まとめて IE 対応を入れる必要ある。そもそも IE って今回は外すんでしたっけ…？
=> 各セクションの最小の高さをウィンドウの高さに合わせる

src/components/parts/MembersVoiceSection.tsx
MembersVoiceSection のダミーデータをやめて、実データを入れたい
- メッセージピックアップ & 追加
- SNS リンク追加
初心者です 😖
=> MembersVoiceSection に実データを投入しました

src/components/App.tsx, src/components/parts/Accordion.tsx, src/components/parts/EntrySection.tsx, src/components/parts/MembersVoiceSection.tsx, src/components/parts/SectionTitle.tsx, src/components/parts/TechnologyStackSection.tsx, src/components/parts/WelfareSection.tsx, src/themes/index.ts, src/themes/palette.ts
`src/themes/palette.ts`を作成し、colorの整理をしました。
よく使用されてるcolorはpalette.tsに定義して使用するように変更しました！
designとcolorが違うところがないか全体をざっと見てもらいたいです！
=> refactor: color定義作成

src/components/parts/EyeCatchEffects.tsx
`background-attachment:fixed;`はiosでは効かないので、iosでも背景画像がfixedされるように修正しました。
=> fix: safariでも背景画像がfixedされるように修正

src/components/parts/WelfareSection.tsx
=> :bug: iPad Pro での Welfare の表示崩れを修正

src/components/parts/EyeCatchEffects.tsx
mobileでスクロールした際、背景画像が拡大されてがたがたしてしまうので、調整しました！
=> fix: adjustment height

src/components/parts/EntrySection.tsx, src/components/parts/EyeCatch.tsx, src/components/parts/WelfareSection.tsx
=> fix: change to the correct link

src/components/pages/ie.tsx, src/pages/index.tsx, types/graphql-types.d.ts
- IE のUA 判定条件に `Trident` を追加
- IE 向け画面に説明を追加
=> IE 向け画面の表示条件修正と説明追加

src/components/pages/ie.tsx, types/graphql-types.d.ts
IE でなぜか想定通りのスタイルが当たらない。
なので styled-comopnents でのスタイル定義ではなく style 属性でやってみる。
=> :bug: スタイルを style 属性で記述する

src/components/parts/MembersVoiceSection.tsx
=> I'm kinoppyd

src/components/parts/Picture.tsx, src/components/parts/WelfareSection.tsx, src/declarations.d.ts
- 型定義はここからパクってきた
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37590#issuecomment-520846460
- alt をシュッとした
=> 福利厚生欄の画像を lazy loding

src/components/parts/AboutSection.tsx
初回読み込み時にiframe内のjsやfontを大量に読み込んでしまっています。
iframe内のリソースは初回読み込み時には必要なさそうなので、iframeのsrcをscrollしてから挿入することで、初回読み込み時の速度改善をしました。
|BEFORE |AFTER  |
|---|---|
|![image](https://user-images.githubusercontent.com/23610884/83085078-d1f95000-a0c5-11ea-8d5a-ee76282a0b9d.png)|![image](https://user-images.githubusercontent.com/23610884/83085016-a1b1b180-a0c5-11ea-88d7-7d3c178a52c4.png)|
=> fix: iframeの遅延読み込み

src/components/parts/TechnologyStackSection.tsx
Plus アプリの技術スタックに AWS と CircleCI を追加しました！
=> update plus app technology stacks

package.json, src/components/App.tsx, src/components/commandPalette/commands/Glitch.tsx, src/components/commandPalette/commands/ImageEffect.tsx, src/components/commandPalette/commands/index.tsx, src/components/commandPalette/commands/shaders/glitch.frag, src/components/commandPalette/commands/shaders/vertexShader.vert, src/components/parts/EyeCatchEffects.tsx, yarn.lock
- canvas のレイヤーが増えたので、スクロールで背景が暗くなる部分の実装方法を変更しています
=> :sparkles: 歴史に残る模範的な glitch コマンドを仕込んだ

src/components/commandPalette/commands/StarryNight.tsx, src/components/commandPalette/commands/index.tsx, src/components/commandPalette/commands/shaders/starryNight.frag
=> :sparkles: 「星見にいこうぜ！」って感じのコマンドを追加した

src/components/parts/EntrySection.tsx
=> remove manager button

src/components/parts/WelfareSection.tsx
=> 福利厚生の英語表記をBenefitsに修正

src/components/parts/EntrySection.tsx
求人票のタイトル変更に伴う修正です。
https://open.talentio.com/1/c/smarthr/requisitions/detail/17020
=> カスタマーサポートOps（開発/データ分析）に職種名を変更

src/components/parts/EntrySection.tsx
=> カスタマーサポートOps（開発/データ分析）を削除

src/components/parts/BenefitsSection.tsx
ref.
- https://shanaiho.smarthr.co.jp/n/nc77ff13bdb46
- https://tech.smarthr.jp/entry/2021/07/05/120106 
I've updated the description for the remote work section because SmartHR has officially announced to allow engineers to work from home 👍 
文言はいい感じに調整してもらえると 🙏
=> feat: introduce full remote work 🎉

src/components/parts/TechnologyStackSection.tsx
=> モニタリングツールにNew Relicを追加

src/components/parts/TechnologyStackSection.tsx
プラスアプリでAWSを採用している物がなくなったので、インフラストラクチャーを更新します
=> goodbye AWS from plus app

src/components/parts/TechnologyStackSection.tsx
=> Update SmartHR Technology Stack

src/components/parts/EntrySection.tsx
SET(Software Engineer in Test) は QA エンジニアとして採用することになったので募集リンクを閉じます。
=> SET は QAエンジニアとして採用することになったのでリンクを削除

src/components/parts/EntrySection.tsx
セキュリティエンジニアは現在募集を停止しており、エントリーページが閲覧できない状態です。
そのため、採用サイトからも動線を消してしまいます。
https://github.com/kufu/hello-world/issues/114
=> セキュリティエンジニアは募集停止中なのでリンクを隠す

src/components/parts/TechnologyStackSection.tsx
フロントエンドのフレームワークはReactが主流となっているため、表記順を修正します。
jQueryも一部残っていますが、適時置き換えが進んでいます。
=> SmartHRのWebアプリケーションフレームワーク順序を整理

src/components/parts/Picture.tsx
こちら対応してみましたので、よろしければご確認いただければ幸いです
- Pictureコンポーネントにて渡された画像ファイル名から拡張子を取り除くコードを見直しました
- 修正前同様に画像が表示されること
=> 画像ファイル名の取得方法リファクタ

src/components/parts/EntrySection.tsx
QAエンジニア（リーダー候補）の募集が開始されたので追加したい。
- QAエンジニア（リーダー候補）を追加しました
- 特になし
=> QAエンジニア（リーダー候補）へのリンクを追加

src/components/sections/Document.astro, src/components/sections/OrganizationalStructure.astro, src/pages/index.astro
「開発組織について」セクションを追加しました
miro のボードを iframe で埋め込んでます
=> [renewal]「開発組織について」セクションを追加

src/components/sections/Positions.astro, src/pages/index.astro, src/services/microcms/types/index.ts
- 求人セクションを追加
- ウェブアプリケーションエンジニアの求人 / 他のエンジニアの求人 / カジュアル面談のそれぞれのリンクを microCMS に追加
=> [renewal] 求人セクションを追加

renovate.json
ライブラリアップデート、やっていきましょう
滞っちゃうとアレなのでdevDepのマイナー・パッチアップデートは自動マージするようにしてみました！
(有効化はmerge後に実施予定です)
=> renovateを設定したい

src/components/sections/Value.astro
| Before | After |
| --- | --- |
| <img width="694" alt="image" src="https://github.com/user-attachments/assets/07f0425a-c483-46f2-9cb6-4dca3f66710e"> | <img width="694" alt="image" src="https://github.com/user-attachments/assets/d963a038-bf40-4279-a588-90eefc612577"> |
=> バリューの記述が最新でないことを注記しておきたいッッ

.github/workflows/lint.yml, package.json
pnpm installによってpackage.jsonの更新が発生していたため、最新化したものをアップします
package.jsonの更新
=> package.jsonの更新
